"""Application configuration and plan policy for ZC Forward Bot."""

from __future__ import annotations

import base64
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final

from dotenv import load_dotenv

load_dotenv()

PLAN_ORDER: Final[dict[str, int]] = {
    "free": 0,
    "plus": 1,
    "pro": 2,
    "infinity": 3,
    "ultra": 4,
}

PLAN_LABELS: Final[dict[str, str]] = {
    "free": "🆓 Free",
    "plus": "⭐ Plus",
    "pro": "💎 Pro",
    "infinity": "♾️ Infinity",
    "ultra": "🚀 Ultra",
}

PLAN_PRICES: Final[dict[str, str]] = {
    "free": "Free",
    "plus": "99 / 30 days",
    "pro": "199 / 30 days",
    "infinity": "299 / 30 days",
    "ultra": "500 / 30 days",
}

# Feature -> lowest plan that can use it. Configuration itself is intentionally free.
FEATURE_PLANS: Final[dict[str, str]] = {
    "settings": "free",
    "forward": "plus",
    "gamma": "pro",
    "watermark": "pro",
    "text_only": "pro",
    "replacer": "infinity",
    "remover": "infinity",
    "link_remover": "infinity",
    "alpha": "infinity",
    "course_seller": "infinity",
    "unequify": "infinity",
    "numbering": "infinity",
    "bullets": "infinity",
    "delta": "ultra",
    "theta": "ultra",
    "pi": "ultra",
}

DEFAULT_FILTERS: Final[dict[str, object]] = {
    "text": True,
    "photo": True,
    "video": True,
    "document": True,
    "audio": True,
    "voice": True,
    "animation": True,
    "sticker": True,
    "poll": True,
    "video_note": True,
    "skip_extensions": [],
    "skip_keywords": [],
    "max_size_mb": 0,
}

DEFAULT_MODES: Final[dict[str, bool]] = {
    "delta": False,
    "alpha": False,
    "gamma": False,
    "theta": False,
    "watermark": False,
    "pi": False,
    "replacer": False,
    "remover": False,
    "link_remover": False,
    "numbering": False,
    "bullets": False,
    "course_seller": False,
    "text_only": False,
}


def default_settings() -> dict[str, Any]:
    """Return a fresh default settings document; never mutate module constants."""
    return {
        "caption": "",
        "buttons": [],
        "filters": {**DEFAULT_FILTERS, "skip_extensions": [], "skip_keywords": []},
        "db_uri_enc": "",
        "modes": DEFAULT_MODES.copy(),
        "watermark": {"prefix": "", "suffix": ""},
        "replacer": {"link": "", "username": "", "pairs": []},
        "numbering": {"style": "{n}.", "start": 1},
        "bullets": {"items": ["📌"], "random": False},
        "seller": {"name": "", "placement": "after"},
        "pi_targets": [],
    }


@dataclass(frozen=True, slots=True)
class Settings:
    api_id: int
    api_hash: str
    bot_token: str
    mongo_uri: str
    encryption_key: str
    owner_ids: frozenset[int]
    main_channel: str
    support_channel: str
    updates_channel: str
    tutorial_channel: str
    admin_username: str
    log_chat_id: int | None
    workdir: Path

    @property
    def admin_url(self) -> str:
        return f"https://t.me/{self.admin_username.lstrip('@')}"

    @property
    def main_channel_url(self) -> str:
        return f"https://t.me/{self.main_channel.lstrip('@')}"

    @property
    def support_url(self) -> str:
        return f"https://t.me/{self.support_channel.lstrip('@')}"

    @property
    def updates_url(self) -> str:
        return f"https://t.me/{self.updates_channel.lstrip('@')}"

    @property
    def tutorial_url(self) -> str:
        return f"https://t.me/{self.tutorial_channel.lstrip('@')}"


def _required(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise RuntimeError(f"{name} is required. Copy .env.example to .env and fill it in.")
    return value


def _owner_ids(value: str) -> frozenset[int]:
    try:
        ids = frozenset(int(item.strip()) for item in value.split(",") if item.strip())
    except ValueError as exc:
        raise RuntimeError("OWNER_IDS must be a comma-separated list of numeric Telegram IDs.") from exc
    if not ids:
        raise RuntimeError("OWNER_IDS must contain at least one numeric Telegram ID.")
    return ids


def load_settings() -> Settings:
    """Load and lightly validate runtime settings without logging any secret."""
    key = _required("ENCRYPTION_KEY")
    try:
        decoded = base64.urlsafe_b64decode(key.encode())
    except Exception as exc:  # Fernet gives a clearer validation later; this catches obvious mistakes.
        raise RuntimeError("ENCRYPTION_KEY must be a Fernet key generated by cryptography.") from exc
    if len(decoded) != 32:
        raise RuntimeError("ENCRYPTION_KEY must be a valid Fernet key (32 decoded bytes).")

    log_chat_raw = os.getenv("LOG_CHAT_ID", "").strip()
    return Settings(
        api_id=int(_required("API_ID")),
        api_hash=_required("API_HASH"),
        bot_token=_required("BOT_TOKEN"),
        mongo_uri=_required("MONGO_URI"),
        encryption_key=key,
        owner_ids=_owner_ids(_required("OWNER_IDS")),
        main_channel=os.getenv("MAIN_CHANNEL", "@ZCYT_29266").strip(),
        support_channel=os.getenv("SUPPORT_CHANNEL", "@ZCYT_2026").strip(),
        updates_channel=os.getenv("UPDATES_CHANNEL", "@ZCYT_2026").strip(),
        tutorial_channel=os.getenv("TUTORIAL_CHANNEL", "@ZCYT_2026").strip(),
        admin_username=os.getenv("ADMIN_USERNAME", "@ZCQXx").strip(),
        log_chat_id=int(log_chat_raw) if log_chat_raw else None,
        workdir=Path(os.getenv("WORKDIR", "./data")).resolve(),
    )


def plan_at_least(plan: str, minimum: str) -> bool:
    return PLAN_ORDER.get(plan, 0) >= PLAN_ORDER[minimum]
